namespace NanoByte.CloneGenerator;

/// <summary>
/// The marker attributes, injected as source into every consuming compilation.
/// </summary>
/// <remarks>
/// They are emitted as <c>internal</c> rather than shipped in a runtime package, so that consumers take no dependency and two consumers can never disagree about a version.
/// </remarks>
internal static class AttributeSource
{
    public const string Namespace = "NanoByte.CloneGenerator";

    public const string CloneableAttribute = $"{Namespace}.CloneableAttribute";
    public const string IgnoreCloneAttribute = $"{Namespace}.IgnoreCloneAttribute";
    public const string ShallowCloneAttribute = $"{Namespace}.ShallowCloneAttribute";
    public const string CloneShallowAttribute = $"{Namespace}.CloneShallowAttribute";

    public const string HintName = "CloneGeneratorAttributes.g.cs";

    public const string Text =
        """
        // <auto-generated/>
        #pragma warning disable
        namespace NanoByte.CloneGenerator
        {
            // Generates a deep Clone() method for this type. The type must be partial.
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("NanoByte.CloneGenerator", null)]
            internal sealed class CloneableAttribute : global::System.Attribute
            {
                // The name of the generated method returning the concrete type. Only used when a base
                // type already declares a Clone() method with a different return type.
                // Defaults to "Clone" + TypeName.
                public string MethodName { get; set; }
            }

            // Excludes this member from the generated clone. The clone keeps the member's default value.
            [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("NanoByte.CloneGenerator", null)]
            internal sealed class IgnoreCloneAttribute : global::System.Attribute
            {}

            // Copies this member by reference, even if its type is cloneable. The clone shares the instance.
            [global::System.AttributeUsage(global::System.AttributeTargets.Property | global::System.AttributeTargets.Field, Inherited = false)]
            [global::System.CodeDom.Compiler.GeneratedCode("NanoByte.CloneGenerator", null)]
            internal sealed class ShallowCloneAttribute : global::System.Attribute
            {}

            // Declares a type as safe to copy by reference, typically because it is immutable.
            // Applies to every member of that type in the assembly.
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
            [global::System.CodeDom.Compiler.GeneratedCode("NanoByte.CloneGenerator", null)]
            internal sealed class CloneShallowAttribute : global::System.Attribute
            {
                public CloneShallowAttribute(global::System.Type type) { Type = type; }

                public global::System.Type Type { get; }
            }
        }
        """;
}
