using System.Text;
using NanoByte.CloneGenerator.Specs;

namespace NanoByte.CloneGenerator;

/// <summary>
/// Writes the generated source for one <see cref="CloneTypeSpec"/>.
/// </summary>
/// <remarks>Works purely on values.</remarks>
internal static class Emitter
{
    public static string Emit(CloneTypeSpec spec, bool supportsNullableContext)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        if (supportsNullableContext) builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable CS0618 // Member is obsolete");
        builder.AppendLine("#pragma warning disable CS0612 // Member is obsolete");
        builder.AppendLine();

        int indent = 0;
        if (spec.Namespace != null)
        {
            builder.AppendLine($"namespace {spec.Namespace}");
            builder.AppendLine("{");
            indent = 1;
        }

        foreach (string declaration in spec.TypeDeclarations)
        {
            builder.AppendLine(Indent(indent) + declaration);
            builder.AppendLine(Indent(indent) + "{");
            indent++;
        }

        bool needsBlankLine = false;
        if (spec.EmitCloneFromTo)
        {
            EmitCloneFromTo(builder, spec, indent);
            needsBlankLine = true;
        }
        if (spec.EmitAbstractClone)
        {
            if (needsBlankLine) builder.AppendLine();
            EmitAbstractClone(builder, spec, indent);
            needsBlankLine = true;
        }
        if (spec.EmitCloneMethod)
        {
            if (needsBlankLine) builder.AppendLine();
            EmitCloneMethod(builder, spec, indent);
            EmitBridges(builder, spec, indent);
        }
        if (spec.EmitSystemCloneable)
        {
            builder.AppendLine();
            builder.AppendLine($"{Indent(indent)}object global::System.ICloneable.Clone() => {spec.CloneMethodName}();");
        }

        foreach (string bridge in spec.InterfaceBridges)
        {
            builder.AppendLine();
            builder.AppendLine(Indent(indent) + bridge);
        }

        for (; indent > 0; indent--)
            builder.AppendLine(Indent(indent - 1) + "}");

        return builder.ToString();
    }

    private static void EmitCloneFromTo(StringBuilder builder, CloneTypeSpec spec, int indent)
    {
        string pad = Indent(indent);
        builder.AppendLine($"{pad}/// <summary>Copies all members declared by <see cref=\"{spec.DocName}\"/> from one instance to another.</summary>");
        // A sealed class cannot introduce protected members (CS0628), and nothing can derive from it anyway
        string accessibility = spec.IsSealed ? "private" : "protected";
        builder.AppendLine($"{pad}{accessibility} static void CloneFromTo({spec.QualifiedName} from, {spec.QualifiedName} to)");
        builder.AppendLine($"{pad}{{");
        builder.AppendLine($"{pad}    if (from == null) throw new global::System.ArgumentNullException(nameof(from));");
        builder.AppendLine($"{pad}    if (to == null) throw new global::System.ArgumentNullException(nameof(to));");

        if (spec.BaseCloneFromTo != null)
            builder.AppendLine($"{pad}    {spec.BaseCloneFromTo}.CloneFromTo(from, to);");

        foreach (var member in spec.Members)
        {
            foreach (string line in SplitLines(member.Code))
                builder.AppendLine($"{pad}    {line}");
        }

        builder.AppendLine($"{pad}}}");
    }

    private static void EmitAbstractClone(StringBuilder builder, CloneTypeSpec spec, int indent)
    {
        string pad = Indent(indent);
        builder.AppendLine($"{pad}/// <summary>Creates a deep copy of this instance.</summary>");
        builder.AppendLine($"{pad}public abstract {spec.CloneReturnType} {spec.CloneMethodName}();");
    }

    private static void EmitCloneMethod(StringBuilder builder, CloneTypeSpec spec, int indent)
    {
        string pad = Indent(indent);
        builder.AppendLine($"{pad}/// <summary>Creates a deep copy of this <see cref=\"{spec.DocName}\"/> instance.</summary>");
        builder.AppendLine($"{pad}/// <returns>The new copy of the <see cref=\"{spec.DocName}\"/>.</returns>");
        builder.AppendLine($"{pad}public {Modifier(spec)}{spec.QualifiedName} {spec.CloneMethodName}()");
        builder.AppendLine($"{pad}{{");
        builder.AppendLine($"{pad}    var from = this;");

        if (spec.InitializerMembers.Count == 0)
            builder.AppendLine($"{pad}    var to = new {spec.QualifiedName}();");
        else
        {
            builder.AppendLine($"{pad}    var to = new {spec.QualifiedName}");
            builder.AppendLine($"{pad}    {{");
            for (int i = 0; i < spec.InitializerMembers.Count; i++)
            {
                var member = spec.InitializerMembers[i];
                string comma = i < spec.InitializerMembers.Count - 1 ? "," : "";
                builder.AppendLine($"{pad}        {member.Name} = {member.Code}{comma}");
            }
            builder.AppendLine($"{pad}    }};");
        }

        builder.AppendLine($"{pad}    CloneFromTo(from, to);");
        builder.AppendLine($"{pad}    return to;");
        builder.AppendLine($"{pad}}}");
    }

    private static void EmitBridges(StringBuilder builder, CloneTypeSpec spec, int indent)
    {
        string pad = Indent(indent);

        if (spec.OverrideReturnType != null)
        {
            builder.AppendLine();
            builder.AppendLine($"{pad}/// <inheritdoc/>");
            builder.AppendLine($"{pad}public override {spec.OverrideReturnType} Clone() => {spec.CloneMethodName}();");
        }

        if (spec.ExplicitGenericInterface != null)
        {
            builder.AppendLine();
            builder.AppendLine($"{pad}{spec.QualifiedName} {spec.ExplicitGenericInterface}.Clone() => {spec.CloneMethodName}();");
        }
    }

    /// <summary>
    /// A root type's <c>Clone()</c> must be virtual so that derived types can override it.
    /// </summary>
    private static string Modifier(CloneTypeSpec spec)
        => spec switch
        {
            {OverrideReturnType: not null} => "",
            {IsSealed: true} => "",
            _ => "virtual "
        };

    private static IEnumerable<string> SplitLines(string code)
        => code.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries);

    private static string Indent(int level) => new(' ', level * 4);
}
